on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: '1.0.0'

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Print Version
        run: |
          echo "Version: ${{ github.event.inputs.version }}"
          node ./script.js ${{ github.event.inputs.version }}
          echo "Done"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: update authors
          title: Bump version ${{ github.event.inputs.version }}
          body: Credit new contributors by ${{ github.event.inputs.version }}
          branch: release/v${{ github.event.inputs.version }}